name: "Setup python"
description: "Setup python version"
inputs:
  python-version:
    description: "Python version to setup"
    required: true
    default: "3.9"
runs:
  using: composite
  steps:
    - name: Setup Python ${{version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{version}}
    - name: Install pip
      run: python -m pip install --upgrade pip
      shell: bash
